name = "blr-cherryblossom"
compatibility_date = "2024-12-01"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "DROPS_KV"
id = "23f9d89f53c947ebb8fe9701a5e73aee"

[[r2_buckets]]
binding = "IMAGES_R2"
bucket_name = "blr-cherryblossom-images"
